{
  "formatVersion": "1.1",
  "component": {
    "group": "ru.breffi.story",
    "module": "storycontent",
    "version": "0.8.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "liburgc4wnbubdpavkfbqzs32y"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.realm",
          "module": "realm-android-library",
          "version": {
            "requires": "10.6.0"
          }
        },
        {
          "group": "io.realm",
          "module": "realm-android-kotlin-extensions",
          "version": {
            "requires": "10.6.0"
          }
        },
        {
          "group": "io.realm",
          "module": "realm-annotations",
          "version": {
            "requires": "10.6.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "javax.inject",
          "module": "javax.inject",
          "version": {
            "requires": "1"
          }
        },
        {
          "group": "com.orhanobut",
          "module": "hawk",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "net.lingala.zip4j",
          "module": "zip4j",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.github.storyclm",
          "module": "story-iot-android",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "com.annimon",
          "module": "stream",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.auth0.android",
          "module": "jwtdecode",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "storycontent-0.8.5.aar",
          "url": "storycontent-0.8.5.aar",
          "size": 650554,
          "sha512": "e25034767507794466d955e1393e00086ae806248bd2ada5d6e56ad1b02bcdfd5b94ea1814705de481e8678dacee84ac319dfa07e97feb1f7810660653aa80b2",
          "sha256": "2e1ab93142114186a76ae66f2cef703f31af00b23a12b8675ad15cc78ac36907",
          "sha1": "0b498ac768ea1ed9b8169c8e63d2f4908ae6573c",
          "md5": "722966ed3a326a0432f923be98256682"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.realm",
          "module": "realm-android-library",
          "version": {
            "requires": "10.6.0"
          }
        },
        {
          "group": "io.realm",
          "module": "realm-android-kotlin-extensions",
          "version": {
            "requires": "10.6.0"
          }
        },
        {
          "group": "io.realm",
          "module": "realm-annotations",
          "version": {
            "requires": "10.6.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "javax.inject",
          "module": "javax.inject",
          "version": {
            "requires": "1"
          }
        },
        {
          "group": "com.orhanobut",
          "module": "hawk",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "net.lingala.zip4j",
          "module": "zip4j",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.github.storyclm",
          "module": "story-iot-android",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "com.annimon",
          "module": "stream",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.auth0.android",
          "module": "jwtdecode",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava2",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.19"
          }
        },
        {
          "group": "com.github.tbruyelle",
          "module": "rxpermissions",
          "version": {
            "requires": "0.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "storycontent-0.8.5.aar",
          "url": "storycontent-0.8.5.aar",
          "size": 650554,
          "sha512": "e25034767507794466d955e1393e00086ae806248bd2ada5d6e56ad1b02bcdfd5b94ea1814705de481e8678dacee84ac319dfa07e97feb1f7810660653aa80b2",
          "sha256": "2e1ab93142114186a76ae66f2cef703f31af00b23a12b8675ad15cc78ac36907",
          "sha1": "0b498ac768ea1ed9b8169c8e63d2f4908ae6573c",
          "md5": "722966ed3a326a0432f923be98256682"
        }
      ]
    }
  ]
}
