{
  "formatVersion": "1.1",
  "component": {
    "group": "ru.breffi.story",
    "module": "storycontent",
    "version": "0.7.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "k6webgo3w5aahlghaib4qmmo4m"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.realm",
          "module": "realm-android-library",
          "version": {
            "requires": "6.0.2"
          }
        },
        {
          "group": "io.realm",
          "module": "realm-android-kotlin-extensions",
          "version": {
            "requires": "6.0.2"
          }
        },
        {
          "group": "io.realm",
          "module": "realm-annotations",
          "version": {
            "requires": "6.0.2"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "javax.inject",
          "module": "javax.inject",
          "version": {
            "requires": "1"
          }
        },
        {
          "group": "com.orhanobut",
          "module": "hawk",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "net.lingala.zip4j",
          "module": "zip4j",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.github.storyclm",
          "module": "story-iot-android",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "com.annimon",
          "module": "stream",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.auth0.android",
          "module": "jwtdecode",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava2",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "3.12.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.19"
          }
        },
        {
          "group": "com.github.tbruyelle",
          "module": "rxpermissions",
          "version": {
            "requires": "0.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "storycontent-0.7.3.aar",
          "url": "storycontent-0.7.3.aar",
          "size": 712488,
          "sha512": "ee5eaf6e0f5c95616e52104538f25a8b8996e8e75050b4bcb4b7290137a655d18a4003f0e367a5cc9c7bb0ab3a5a1afe065ef2bcda835e2fda1f13f1b130352e",
          "sha256": "7a7430e9cbf2e6383ed4a9fe00337cf926e52720b692a55bf2f936fbb6c615d1",
          "sha1": "e612e53ecdf66d5cd537227c11feb430f63613f6",
          "md5": "441c491cbdf83bdcfe1973935bf4043b"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.realm",
          "module": "realm-android-library",
          "version": {
            "requires": "6.0.2"
          }
        },
        {
          "group": "io.realm",
          "module": "realm-android-kotlin-extensions",
          "version": {
            "requires": "6.0.2"
          }
        },
        {
          "group": "io.realm",
          "module": "realm-annotations",
          "version": {
            "requires": "6.0.2"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "javax.inject",
          "module": "javax.inject",
          "version": {
            "requires": "1"
          }
        },
        {
          "group": "com.orhanobut",
          "module": "hawk",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "net.lingala.zip4j",
          "module": "zip4j",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.github.storyclm",
          "module": "story-iot-android",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "com.annimon",
          "module": "stream",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.auth0.android",
          "module": "jwtdecode",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "storycontent-0.7.3.aar",
          "url": "storycontent-0.7.3.aar",
          "size": 712488,
          "sha512": "ee5eaf6e0f5c95616e52104538f25a8b8996e8e75050b4bcb4b7290137a655d18a4003f0e367a5cc9c7bb0ab3a5a1afe065ef2bcda835e2fda1f13f1b130352e",
          "sha256": "7a7430e9cbf2e6383ed4a9fe00337cf926e52720b692a55bf2f936fbb6c615d1",
          "sha1": "e612e53ecdf66d5cd537227c11feb430f63613f6",
          "md5": "441c491cbdf83bdcfe1973935bf4043b"
        }
      ]
    }
  ]
}
