{
  "formatVersion": "1.1",
  "component": {
    "group": "ru.breffi.story",
    "module": "storycontent",
    "version": "0.7.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "yz5tt3ja5vgfxp5hxxky3ekjc4"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.realm",
          "module": "realm-android-library",
          "version": {
            "requires": "6.0.2"
          }
        },
        {
          "group": "io.realm",
          "module": "realm-android-kotlin-extensions",
          "version": {
            "requires": "6.0.2"
          }
        },
        {
          "group": "io.realm",
          "module": "realm-annotations",
          "version": {
            "requires": "6.0.2"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "javax.inject",
          "module": "javax.inject",
          "version": {
            "requires": "1"
          }
        },
        {
          "group": "com.orhanobut",
          "module": "hawk",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "net.lingala.zip4j",
          "module": "zip4j",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.github.storyclm",
          "module": "story-iot-android",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "com.annimon",
          "module": "stream",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.auth0.android",
          "module": "jwtdecode",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava2",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "3.12.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.19"
          }
        },
        {
          "group": "com.github.tbruyelle",
          "module": "rxpermissions",
          "version": {
            "requires": "0.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "storycontent-0.7.5.aar",
          "url": "storycontent-0.7.5.aar",
          "size": 712914,
          "sha512": "b3f7919ee60bd0646986e1875eb863df3b8ebdeab2994acc2e97a39ef7fb78798d13d542fff36c164359127aee317c266ff3679632e4489a1c15de45403de467",
          "sha256": "818460340f708dadaddef53e13175d01ea4f95709e098700b611384abce5eae0",
          "sha1": "b7140874cb3069efdd0a34c6122da933d1251c88",
          "md5": "5d66496d7c1ddb5110bee12aee7f13b9"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.realm",
          "module": "realm-android-library",
          "version": {
            "requires": "6.0.2"
          }
        },
        {
          "group": "io.realm",
          "module": "realm-android-kotlin-extensions",
          "version": {
            "requires": "6.0.2"
          }
        },
        {
          "group": "io.realm",
          "module": "realm-annotations",
          "version": {
            "requires": "6.0.2"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "javax.inject",
          "module": "javax.inject",
          "version": {
            "requires": "1"
          }
        },
        {
          "group": "com.orhanobut",
          "module": "hawk",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "net.lingala.zip4j",
          "module": "zip4j",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.github.storyclm",
          "module": "story-iot-android",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "com.annimon",
          "module": "stream",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.auth0.android",
          "module": "jwtdecode",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "storycontent-0.7.5.aar",
          "url": "storycontent-0.7.5.aar",
          "size": 712914,
          "sha512": "b3f7919ee60bd0646986e1875eb863df3b8ebdeab2994acc2e97a39ef7fb78798d13d542fff36c164359127aee317c266ff3679632e4489a1c15de45403de467",
          "sha256": "818460340f708dadaddef53e13175d01ea4f95709e098700b611384abce5eae0",
          "sha1": "b7140874cb3069efdd0a34c6122da933d1251c88",
          "md5": "5d66496d7c1ddb5110bee12aee7f13b9"
        }
      ]
    }
  ]
}
